Algoritmo "Exercicio12"

// Autor(a): Jorge Siqueira
// Data: 04/08/2026

//Exercício 12 –Contagem regressiva: Crie um algoritmo que exiba os números de 10 até 1 e no final escreva “Feliz Ano novo!”

Var
   i: Inteiro   // variável contadora

Inicio
   // Laço: i começa em 10, vai até 1, diminuindo 1 a cada repetição
   Para i de 10 ate 1 passo -1 faca
      Escreval(i)   // exibe o número atual
   FimPara

   // Mensagem final após a contagem
   Escreval("Feliz Ano novo!")
FimAlgoritmo